accelerator: gpu
batch_size: 16
bench_data_path: data/3_bench
decay: 1.0e-08
device: cuda
devices: 1
dropout_ratio: 0.1
epochs: 100
experiment_name: sgd
filter_size: 5
gradient_clip_val: 0.1
hidden_channels: 64
image_size: 512
in_channels: 3
infer_data_path: data/4_infer
inference: inference
log_dir: ./runs/HomomorphicUnet/optims
log_every_n_steps: 5
lr: 1.0e-07
max_epochs: 100
num_levels: 4
num_workers: 10
omega_x: 0.25
omega_y: 0.25
optim: sgd
out_channels: 3
patience: 30
precision: 32
save_dir: ./runs/HomomorphicUnet/optims/st
seed: 42
shortcut: true
sigma: 1.0
squeeze_ratio: 0.3
temb_dim: 64
timesteps: 1000
train_data_path: data/1_train
trainable: false
valid_data_path: data/2_valid
